### ISSUE TITLE
Markdown processor for articles

### ISSUE THREAD

**Issue by mhinz** [vimmer-net/website#1]
It should be as easy as possible to contribute. People should be able to simple make a pull request for an article written in Markdown.

After review, when it gets merged.. when do we publish it? Manually? Automatically via cron?

**Comment by tweekmonster** [comment]
> After review, when it gets merged.. when do we publish it? Manually? Automatically via cron?

Webhooks!

**Comment by tweekmonster** [comment]
A separate repository to use as a CMS for blog/article content might be best/easiest.  Users can submit/correct articles through PRs.  I propose the layout:

```
/YYYY-MM/article-slug/index.md
```

The `YYYY-MM` prefix keeps the repo index from getting too long.  `YYYY-MM/article-slug` keeps the article and any supporting files (such as images) contained.

On the server, `/YYYY-MM/article-slug/.index.html` (ignored by git) would be the cached `index.md` render.  On request, if `index.md` is newer than `.index.html` re-render and serve `.index.html`.  The rendered `.index.html` should only contain the HTML for the article itself.  The web app would wrap the rendered content with the site-wide template on each request.

The markdown parser should be able to handle the basic metadata described here: https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide

Problems with this idea:

- No future scheduling of articles
  - Surprise announcements would be impossible
- The Github repo might compete with the website on search engines
- Content could be re-pubilshed/mentioned/stolen with low effort, before published on the site.
